"""Contact Forecast R1: the artifact -> report path.

The report is generated by walking the machine-readable artifacts, which is
what makes "negative results are preserved" a structural property rather than
a matter of authorial discipline. These tests build an artifact in which the
challenger LOSES and check that the loss is rendered, with its sign intact.

Synthetic data only.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from forecast.bootstrap import BootstrapDesign
from forecast.forecast_config import (
    BASELINE_LADDER,
    CONTACT_STAGE_DISCLAIMER,
    PRIMARY_COMPARISON,
)
from forecast.report import render_report
from forecast.run_r1_analysis import (
    build_bootstrap_artifact,
    build_metrics_artifact,
)
from forecast.targets import assert_no_banned_metric_language

REFERENCE, CHALLENGER = PRIMARY_COMPARISON


def make_table(*, challenger_wins: bool, seed: int = 21) -> pd.DataFrame:
    """A prediction table with the ladder columns the artifact builders expect."""
    rng = np.random.default_rng(seed)
    rows: list[dict[str, object]] = []
    challenger_noise = 2.0 if challenger_wins else 11.0
    for season in (2023, 2024):
        for cutoff, horizon in ((100, 100), (50, 50)):
            for batter in range(40):
                truth = rng.normal(4.0, 5.0)
                realized = truth + rng.normal(0.0, 7.0)
                rows.append(
                    {
                        "window_id": f"{batter}-{season}-{cutoff}-{horizon}",
                        "batter": batter,
                        "season": season,
                        "cutoff": cutoff,
                        "horizon": horizon,
                        "target_realized_rv_per_100": realized,
                        "target_deserved_rv_per_100": truth + rng.normal(0.0, 3.0),
                        "std_realized_rv_per_100": truth + rng.normal(0.0, 6.0),
                        "std_deserved_rv_per_100": truth + rng.normal(0.0, 3.0),
                        "league_mean": 4.0,
                        "raw_realized_persistence": truth + rng.normal(0.0, 6.0),
                        "raw_deserved_persistence": truth + rng.normal(0.0, 4.0),
                        REFERENCE: truth + rng.normal(0.0, 6.0),
                        CHALLENGER: truth + rng.normal(0.0, challenger_noise),
                    }
                )
    return pd.DataFrame(rows)


def build_artifacts(table: pd.DataFrame) -> tuple[dict, dict]:
    metrics = build_metrics_artifact(table, {"n_windows": int(len(table))})
    bootstrap = build_bootstrap_artifact(table, design=BootstrapDesign(reps=30, seed=1))
    return metrics, bootstrap


def empty_regression_artifact() -> dict:
    return {
        "regression_direction_by_cell": {},
        "direction_probability": {
            "event": "decline",
            "training_rule": "fit on strictly earlier seasons",
            "models": {},
            "cells": {},
        },
    }


# --------------------------------------------------------------------------
# Negative results survive the write-up
# --------------------------------------------------------------------------


def test_a_losing_challenger_is_rendered_as_losing() -> None:
    table = make_table(challenger_wins=False)
    metrics, bootstrap = build_artifacts(table)
    cell = metrics["cells"]["target_realized_rv_per_100|K100_H100"]
    pooled = cell["comparisons"][CHALLENGER]["pooled_window_weighted"]
    assert pooled["delta_mae"] > 0
    assert pooled["direction_mae"] == "reference_better"

    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "realized better" in report
    # The positive delta is printed as printed, not re-oriented.
    assert f"{pooled['delta_mae']:.4f}" in report


def test_the_report_never_prints_a_reversed_delta() -> None:
    for challenger_wins in (True, False):
        table = make_table(challenger_wins=challenger_wins)
        metrics, bootstrap = build_artifacts(table)
        report = render_report(
            metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
        )
        for key, cell in metrics["cells"].items():
            if cell.get("status") == "no_windows":
                continue
            for comparison in cell["comparisons"].values():
                if comparison.get("status") != "measured":
                    continue
                delta = comparison["pooled_window_weighted"]["delta_mae"]
                # Matched as a whole table cell, so "-0.66" is not mistaken
                # for a match on "0.66".
                assert f"| {delta:.4f} |" in report, key
                if delta != 0.0:
                    assert f"| {-delta:.4f} |" not in report, key


def test_every_measured_comparison_reaches_the_report() -> None:
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    measured = 0
    for cell in metrics["cells"].values():
        if cell.get("status") == "no_windows":
            continue
        for challenger, comparison in cell["comparisons"].items():
            if comparison.get("status") != "measured":
                continue
            measured += 1
            assert f"`{challenger}`" in report
    assert measured == len(BASELINE_LADDER[1:]) * 2 * 2  # rungs x cells x targets
    assert report.count("| deserved |") + report.count("| realized |") >= measured


def test_the_full_ladder_including_the_constant_rung_is_reported() -> None:
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "`league_mean`" in report
    # A constant predictor's correlations must read as undefined, not as 0.
    assert "undefined (undefined_constant_predictor)" in report


# --------------------------------------------------------------------------
# Mandatory framing
# --------------------------------------------------------------------------


def test_the_report_states_the_sign_convention_in_full() -> None:
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "negative -> deserved is better" in report
    assert "zero     -> no difference" in report
    assert "positive -> realized is better" in report


def test_the_report_carries_the_contact_stage_and_conditional_language() -> None:
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert CONTACT_STAGE_DISCLAIMER in report
    assert "CONDITIONAL ON" in report
    assert "does not predict continued playing time" in report


def test_the_report_passes_the_banned_phrase_guard() -> None:
    """Only the disclaimer's own negated use of the phrase is exempt."""
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert_no_banned_metric_language(report.replace(CONTACT_STAGE_DISCLAIMER, ""))


def test_the_focal_view_is_marked_without_narrowing_the_specification() -> None:
    """100 -> 100 leads the report but does not outrank the other cutoffs.

    The pre-designation claim is not provable from repository history, so the
    original multi-cutoff specification stands and this cell is a presentation
    view only.
    """
    table = make_table(challenger_wins=False)
    metrics, bootstrap = build_artifacts(table)
    focal = metrics["specification"]["focal_presentation_view"]
    assert focal["cutoff"] == 100
    assert focal["horizon"] == 100
    assert focal["designation_provable_from_repository_history"] is False
    assert "NOT a narrowing" in focal["status"]
    assert focal["primary_family_unchanged"] == [50, 100, 150, 200]
    assert focal["no_conclusion_rests_on_this_cell"] is True
    assert metrics["cells"]["target_realized_rv_per_100|K100_H100"]["is_focal_presentation_view"]
    assert not metrics["cells"]["target_realized_rv_per_100|K50_H50"]["is_focal_presentation_view"]

    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "*(focal view)*" in report
    assert "presentation view only" in report


def test_the_report_never_calls_the_focal_cell_a_headline_result() -> None:
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "## Headline result" not in report
    assert "## Focal presentation view" in report


def test_a_cell_with_no_windows_is_recorded_not_omitted() -> None:
    table = make_table(challenger_wins=True)
    metrics, _ = build_artifacts(table)
    # The grid has eight cells per target; only two carry synthetic windows.
    empty = [c for c in metrics["cells"].values() if c.get("status") == "no_windows"]
    assert empty
    for cell in empty:
        assert cell["n_windows"] == 0
        assert "cutoff" in cell and "horizon" in cell


def test_undefined_correlations_serialize_as_null_not_zero() -> None:
    table = make_table(challenger_wins=True)
    metrics, _ = build_artifacts(table)
    cell = metrics["cells"]["target_realized_rv_per_100|K100_H100"]
    league = next(m for m in cell["ladder_pooled"]["metrics"] if m["predictor"] == "league_mean")
    assert league["pearson"] is None
    assert league["spearman"] is None
    assert league["mae"] > 0


def test_a_rung_constant_within_each_season_is_labelled_as_such() -> None:
    """`league_mean` varies across seasons only; that must not read as skill."""
    table = make_table(challenger_wins=True)
    metrics, bootstrap = build_artifacts(table)
    # Give each season its own league mean, as the real ladder does.
    table.loc[table["season"] == 2023, "league_mean"] = 3.9
    table.loc[table["season"] == 2024, "league_mean"] = 4.3
    metrics, bootstrap = build_artifacts(table)

    cell = metrics["cells"]["target_realized_rv_per_100|K100_H100"]
    league = next(m for m in cell["ladder_pooled"]["metrics"] if m["predictor"] == "league_mean")
    assert league["constant_within_every_season"] is True
    assert league["pearson"] is not None  # pooled, it does vary
    # Per season it is genuinely constant, so the correlation is undefined.
    for season_entry in cell["ladder_by_season"].values():
        seasonal = next(m for m in season_entry["metrics"] if m["predictor"] == "league_mean")
        assert seasonal["pearson"] is None
        assert seasonal["pearson_status"] == "undefined_constant_predictor"

    report = render_report(
        metrics=metrics, bootstrap=bootstrap, regression=empty_regression_artifact()
    )
    assert "between-season variation only" in report
