"""Contact Forecast R1: run the prespecified analysis and write every artifact.

This is the entry point for R1's descriptive stage. It fits NO forecasting
model -- no ridge, no gradient boosting, nothing beyond the frozen baseline
ladder, the matched shrinkage the ladder already specifies, and the
regression-direction experiment's ordinary least squares and its logistic
direction-probability mapping. Those are the analysis, not a candidate
forecaster.

What it produces, all under `forecast_config.FORECAST_OUTPUTS_DIR`:

  - `r1_prediction_table.parquet` -- one row per window with both targets,
    the pre-cutoff features and every ladder rung. Everything else is derived
    from this, so re-running any single analysis needs only this file.
  - `r1_metrics.json` -- every prespecified cell, every ladder rung, per
    season and pooled, with the macro-average and the batter-balanced
    sensitivity.
  - `r1_bootstrap.json` -- paired, globally batter-clustered intervals.
  - `r1_regression_direction.json` -- the regression-direction experiment,
    its permutation placebo, and the walk-forward decline-probability models.
  - `r1_report.md` -- the human-readable report, generated from those
    artifacts and from nothing else.

## Negative results are structural here, not a matter of discipline

The report is generated by walking the artifact, so a cell cannot be omitted
from the write-up without being omitted from the data. Cells where realized
beats deserved, where an interval crosses zero, where a correlation is weak,
and where the placebo explains the whole regression-direction signal are
rendered by the same code path as favourable ones.
"""

from __future__ import annotations

import argparse
import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from forecast.assemble import RUNG_AVAILABILITY, build_prediction_table
from forecast.bootstrap import BootstrapDesign, run_paired_bootstrap
from forecast.forecast_config import (
    BASELINE_LADDER,
    CONTACT_STAGE_DISCLAIMER,
    DEFAULT_BOOTSTRAP_ALPHA,
    DEFAULT_BOOTSTRAP_REPS,
    DEFAULT_BOOTSTRAP_SEED,
    FOCAL_PRESENTATION_CUTOFF,
    FORECAST_ANALYSIS_SEASONS,
    FORECAST_DATA_DIR,
    FORECAST_OUTPUTS_DIR,
    PRIMARY_COMPARISON,
    PRIMARY_CUTOFFS,
    PRIMARY_HORIZON,
    PRIMARY_TARGET,
    assert_path_outside_forbidden_namespaces,
    conditional_forecast_language,
    window_grid,
)
from forecast.metrics import (
    DELTA_SIGN_CONVENTION,
    assert_delta_convention,
    batter_balanced_delta,
    describe_practical_magnitude,
    evaluate_ladder,
    evaluate_predictor,
    macro_average_delta,
    paired_delta,
    per_season_deltas,
)
from forecast.regression_direction import (
    DEFAULT_PERMUTATIONS,
    run_direction_probability,
    run_regression_direction_cell,
)
from forecast.targets import (
    TARGET_LABELS,
    assert_no_banned_metric_language,
    describe_target,
    summarize_repeated_window_structure,
    target_columns,
)

logger = logging.getLogger(__name__)

REFERENCE_RUNG, CHALLENGER_RUNG = PRIMARY_COMPARISON

#: Ladder rungs compared against the reference rung, in report order. Every
#: one is bootstrapped, including the ones expected to lose.
CHALLENGER_RUNGS: tuple[str, ...] = tuple(r for r in BASELINE_LADDER if r != REFERENCE_RUNG)


def _json_default(value: Any) -> Any:
    """Serialize numpy scalars; refuse anything genuinely unserializable."""
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        number = float(value)
        return number if np.isfinite(number) else None
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    raise TypeError(f"{type(value)!r} is not JSON-serializable")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    assert_path_outside_forbidden_namespaces(path)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, default=_json_default))
    logger.info("wrote %s", path)


def _paired_subset(
    table: pd.DataFrame, *, target: str, reference: str, challenger: str
) -> pd.DataFrame:
    """Rows where the target and BOTH predictors are present.

    Restricting once, here, is what keeps every downstream comparison paired.
    A season that loses every row -- 2022 for any shrunk-deserved comparison
    -- disappears from the pair rather than being silently half-counted, and
    the caller reports which seasons survived.
    """
    return table.dropna(subset=[target, reference, challenger]).copy()


def _constant_within_every_season(frame: pd.DataFrame, predictor: str) -> bool:
    """Whether `predictor` takes a single value inside each season separately.

    True for `league_mean`, which is one prior-season league rate per season.
    Such a rung varies across the pooled frame only because the seasons
    differ, so any pooled correlation it shows is a between-season artifact.
    """
    present = frame.dropna(subset=[predictor])
    if present.empty:
        return False
    by_season = present.groupby(present["season"].astype(int))[predictor]
    return bool((by_season.max() == by_season.min()).all())


def _cell_key(cutoff: int, horizon: int) -> str:
    return f"K{int(cutoff)}_H{int(horizon)}"


def build_metrics_artifact(table: pd.DataFrame, audit: dict[str, Any]) -> dict[str, Any]:
    """Every prespecified cell: ladder metrics, deltas, macro and batter-balanced."""
    cells: dict[str, Any] = {}
    for target in target_columns():
        for cutoff, horizon in window_grid():
            cell_rows = table[
                (table["cutoff"].astype(int) == cutoff) & (table["horizon"].astype(int) == horizon)
            ]
            key = f"{target}|{_cell_key(cutoff, horizon)}"
            cells[key] = _build_cell(cell_rows, target=target, cutoff=cutoff, horizon=horizon)

    return {
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "sign_convention": DELTA_SIGN_CONVENTION,
        "specification": {
            "focal_presentation_view": {
                "cutoff": FOCAL_PRESENTATION_CUTOFF,
                "horizon": PRIMARY_HORIZON,
                "target": PRIMARY_TARGET,
                "statement": (
                    f"{FOCAL_PRESENTATION_CUTOFF} BBE observed -> next {PRIMARY_HORIZON} "
                    "BBE realized RV/100"
                ),
                "status": "presentation view only, NOT a narrowing of the specification",
                "designation_provable_from_repository_history": False,
                "why": (
                    "A product-focused amendment proposed making this the single "
                    "headline cell. Repository history cannot prove the designation "
                    "preceded the first computed metric -- forecast/ was untracked, so "
                    "no commit timestamps it -- so the amendment was NOT adopted and "
                    "the original multi-cutoff specification stands."
                ),
                "primary_family_unchanged": list(PRIMARY_CUTOFFS),
                "no_conclusion_rests_on_this_cell": True,
            },
            "primary_comparison": {
                "reference": REFERENCE_RUNG,
                "challenger": CHALLENGER_RUNG,
                "why": (
                    "Equivalently-shrunk realized versus equivalently-shrunk deserved "
                    "is the only rung pair that separates a luck-adjusted contact "
                    "signal from generic regression to the mean."
                ),
            },
            "baseline_ladder": list(BASELINE_LADDER),
            "all_other_cells_are": "prespecified robustness analyses, reported in full",
            "contact_stage_disclaimer": CONTACT_STAGE_DISCLAIMER,
            "conditional_forecast": {str(h): conditional_forecast_language(h) for h in (50, 100)},
        },
        "rung_availability_by_season": {
            str(s): RUNG_AVAILABILITY[int(s)] for s in FORECAST_ANALYSIS_SEASONS
        },
        "repeated_window_structure": summarize_repeated_window_structure(table),
        "assembly_audit": audit,
        "cells": cells,
    }


def _build_cell(
    cell_rows: pd.DataFrame, *, target: str, cutoff: int, horizon: int
) -> dict[str, Any]:
    """One (target, cutoff, horizon) cell: ladder, deltas, macro, sensitivity."""
    is_focal_view = (
        target == PRIMARY_TARGET
        and int(cutoff) == FOCAL_PRESENTATION_CUTOFF
        and int(horizon) == PRIMARY_HORIZON
    )
    record: dict[str, Any] = {
        "target": target,
        "target_label": TARGET_LABELS[target],
        "cutoff": int(cutoff),
        "horizon": int(horizon),
        "is_focal_presentation_view": is_focal_view,
        "is_primary_family": target == PRIMARY_TARGET and int(horizon) == PRIMARY_HORIZON,
        "conditional_interpretation": describe_target(target, horizon),
        "n_windows": int(len(cell_rows)),
        "n_unique_batters": int(cell_rows["batter"].nunique()) if len(cell_rows) else 0,
    }
    if cell_rows.empty:
        record["status"] = "no_windows"
        return record

    record["target_sd"] = float(cell_rows[target].std(ddof=1))
    record["ladder_by_season"] = {
        str(season): {
            "n": int(len(season_rows)),
            "target_sd": float(season_rows[target].std(ddof=1)),
            "metrics": [
                m.as_record()
                for m in evaluate_ladder(
                    season_rows.dropna(subset=[target]), target=target, predictors=BASELINE_LADDER
                )
            ],
        }
        for season, season_rows in (
            (int(s), cell_rows[cell_rows["season"].astype(int) == int(s)])
            for s in sorted(cell_rows["season"].astype(int).unique())
        )
    }
    pooled_metrics = []
    for measured in evaluate_ladder(cell_rows, target=target, predictors=BASELINE_LADDER):
        pooled_record = measured.as_record()
        # `league_mean` is one constant PER SEASON, not one constant overall:
        # each season's value is its own prior-season league rate. Pooled
        # across seasons it therefore has a defined correlation, driven
        # entirely by between-season differences and carrying no within-season
        # ranking information at all. Flagged so that number can never be read
        # as rank skill.
        pooled_record["constant_within_every_season"] = _constant_within_every_season(
            cell_rows, measured.predictor
        )
        pooled_metrics.append(pooled_record)
    record["ladder_pooled"] = {
        "n": int(len(cell_rows)),
        "note": (
            "each rung measured on its own complete cases; rungs with different "
            "season coverage are NOT directly comparable here -- the paired "
            "comparisons below are"
        ),
        "metrics": pooled_metrics,
    }
    record["comparisons"] = {
        challenger: _build_comparison(
            cell_rows, target=target, reference=REFERENCE_RUNG, challenger=challenger
        )
        for challenger in CHALLENGER_RUNGS
    }
    return record


def _build_comparison(
    cell_rows: pd.DataFrame, *, target: str, reference: str, challenger: str
) -> dict[str, Any]:
    """One paired comparison inside one cell, with every required view."""
    paired = _paired_subset(cell_rows, target=target, reference=reference, challenger=challenger)
    seasons_present = sorted(int(s) for s in cell_rows["season"].astype(int).unique())
    seasons_paired = sorted(int(s) for s in paired["season"].astype(int).unique())
    dropped = [s for s in seasons_present if s not in seasons_paired]

    record: dict[str, Any] = {
        "reference": reference,
        "challenger": challenger,
        "n_paired_windows": int(len(paired)),
        "seasons_in_comparison": seasons_paired,
        "seasons_excluded_for_missing_rung": dropped,
        "exclusion_reason": (
            RUNG_AVAILABILITY.get(dropped[0], {}).get("reason") if dropped else None
        ),
    }
    if paired.empty:
        record["status"] = "no_paired_windows"
        return record

    pooled = paired_delta(paired, target=target, reference=reference, challenger=challenger)
    assert_delta_convention(pooled)
    season_deltas = per_season_deltas(
        paired, target=target, reference=reference, challenger=challenger
    )
    for delta in season_deltas.values():
        assert_delta_convention(delta)
    balanced = batter_balanced_delta(
        paired, target=target, reference=reference, challenger=challenger
    )
    assert_delta_convention(balanced)

    record["status"] = "measured"
    record["pooled_window_weighted"] = pooled.as_record()
    record["by_season"] = {str(s): d.as_record() for s, d in season_deltas.items()}
    record["macro_average_of_season_deltas"] = macro_average_delta(season_deltas)
    record["batter_balanced"] = {
        "definition": (
            "loss averaged WITHIN each batter first, then each unique batter weighted equally"
        ),
        "n_unique_batters": balanced.n,
        "delta": balanced.as_record(),
        "sign_matches_window_weighted": (balanced.direction_mae == pooled.direction_mae),
        "magnitude_shift_delta_mae": float(balanced.delta_mae - pooled.delta_mae),
    }
    record["practical_magnitude"] = describe_practical_magnitude(
        pooled, target_sd=float(paired[target].std(ddof=1))
    )
    record["reference_metrics"] = evaluate_predictor(
        paired, target=target, predictor=reference
    ).as_record()
    record["challenger_metrics"] = evaluate_predictor(
        paired, target=target, predictor=challenger
    ).as_record()
    return record


def build_bootstrap_artifact(table: pd.DataFrame, *, design: BootstrapDesign) -> dict[str, Any]:
    """Paired batter-clustered intervals for every ladder comparison and target."""
    comparisons: dict[str, Any] = {}
    for target in target_columns():
        for challenger in CHALLENGER_RUNGS:
            paired = _paired_subset(
                table, target=target, reference=REFERENCE_RUNG, challenger=challenger
            )
            key = f"{target}|{challenger}_vs_{REFERENCE_RUNG}"
            if paired.empty:
                comparisons[key] = {"status": "no_paired_windows"}
                continue
            logger.info(
                "bootstrapping %s (%d paired windows, %d batters)",
                key,
                len(paired),
                paired["batter"].nunique(),
            )
            comparisons[key] = run_paired_bootstrap(
                paired,
                target=target,
                reference=REFERENCE_RUNG,
                challenger=challenger,
                design=design,
            )
            comparisons[key]["seasons_in_comparison"] = sorted(
                int(s) for s in paired["season"].astype(int).unique()
            )
    return {
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "sign_convention": DELTA_SIGN_CONVENTION,
        "design": design.as_record(),
        "comparisons": comparisons,
    }


def build_regression_direction_artifact(
    table: pd.DataFrame, *, permutations: int, seed: int
) -> dict[str, Any]:
    """The regression-direction experiment, its placebo, and direction probability."""
    cells: dict[str, Any] = {}
    for cutoff, horizon in window_grid():
        for season in sorted(table["season"].astype(int).unique()):
            rows = table[
                (table["cutoff"].astype(int) == cutoff)
                & (table["horizon"].astype(int) == horizon)
                & (table["season"].astype(int) == int(season))
            ]
            key = f"{_cell_key(cutoff, horizon)}_season{int(season)}"
            logger.info("regression-direction %s (%d windows)", key, len(rows))
            cells[key] = {
                "cutoff": int(cutoff),
                "horizon": int(horizon),
                "season": int(season),
                "is_focal_presentation_view": (
                    int(cutoff) == FOCAL_PRESENTATION_CUTOFF and int(horizon) == PRIMARY_HORIZON
                ),
                **run_regression_direction_cell(rows, permutations=permutations, seed=seed),
            }
    return {
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "contact_stage_disclaimer": CONTACT_STAGE_DISCLAIMER,
        "permutations": permutations,
        "seed": seed,
        "regression_direction_by_cell": cells,
        "direction_probability": run_direction_probability(table),
    }


def run(
    *,
    seasons: tuple[int, ...] = FORECAST_ANALYSIS_SEASONS,
    data_dir: Path = FORECAST_DATA_DIR,
    output_dir: Path = FORECAST_OUTPUTS_DIR,
    reps: int = DEFAULT_BOOTSTRAP_REPS,
    seed: int = DEFAULT_BOOTSTRAP_SEED,
    alpha: float = DEFAULT_BOOTSTRAP_ALPHA,
    permutations: int = DEFAULT_PERMUTATIONS,
) -> dict[str, Path]:
    """Assemble, measure, bootstrap, probe, and write every artifact."""
    assert_path_outside_forbidden_namespaces(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    table, audit = build_prediction_table(seasons=seasons, data_dir=data_dir)
    table_path = output_dir / "r1_prediction_table.parquet"
    table.to_parquet(table_path, index=False)
    logger.info("wrote %s (%d windows)", table_path, len(table))

    metrics = build_metrics_artifact(table, audit)
    _write_json(output_dir / "r1_metrics.json", metrics)

    design = BootstrapDesign(reps=reps, seed=seed, alpha=alpha)
    bootstrap = build_bootstrap_artifact(table, design=design)
    _write_json(output_dir / "r1_bootstrap.json", bootstrap)

    regression = build_regression_direction_artifact(table, permutations=permutations, seed=seed)
    _write_json(output_dir / "r1_regression_direction.json", regression)

    from forecast.report import render_report

    report = render_report(metrics=metrics, bootstrap=bootstrap, regression=regression)
    # CONTACT_STAGE_DISCLAIMER itself contains "the published Contact Luck
    # metric" -- inside a NEGATION, which is the one sanctioned use of the
    # phrase and the whole reason the disclaimer exists. It is removed by
    # EXACT string identity before the ban check, so the guard still catches
    # every other occurrence, including a paraphrase of the disclaimer that
    # dropped the negation.
    assert_no_banned_metric_language(report.replace(CONTACT_STAGE_DISCLAIMER, ""))
    report_path = output_dir / "r1_report.md"
    report_path.write_text(report)
    logger.info("wrote %s", report_path)

    return {
        "prediction_table": table_path,
        "metrics": output_dir / "r1_metrics.json",
        "bootstrap": output_dir / "r1_bootstrap.json",
        "regression_direction": output_dir / "r1_regression_direction.json",
        "report": report_path,
    }


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seasons", type=int, nargs="+", default=list(FORECAST_ANALYSIS_SEASONS))
    parser.add_argument("--data-dir", type=Path, default=FORECAST_DATA_DIR)
    parser.add_argument("--output-dir", type=Path, default=FORECAST_OUTPUTS_DIR)
    parser.add_argument("--bootstrap-reps", type=int, default=DEFAULT_BOOTSTRAP_REPS)
    parser.add_argument("--permutations", type=int, default=DEFAULT_PERMUTATIONS)
    parser.add_argument("--seed", type=int, default=DEFAULT_BOOTSTRAP_SEED)
    parser.add_argument("--alpha", type=float, default=DEFAULT_BOOTSTRAP_ALPHA)
    return parser


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    args = build_arg_parser().parse_args(argv)
    written = run(
        seasons=tuple(args.seasons),
        data_dir=args.data_dir,
        output_dir=args.output_dir,
        reps=args.bootstrap_reps,
        seed=args.seed,
        alpha=args.alpha,
        permutations=args.permutations,
    )
    for name, path in written.items():
        print(f"{name}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
