"""Contact Forecast: the H=200 forecast specification, frozen on development data.

## The provenance question, answered first

The exploratory 100 -> 200 scoping result was produced by **REFITTING** Model D
on next-200-BBE targets. It was NOT the frozen H=100 coefficients applied to a
longer evaluation window. Measured directly: coefficients differ, standard
-scaler statistics differ, the intercept moves 5.2184 -> 5.8165, and the
training set shrinks 564 -> 336 rows because a 300-BBE requirement qualifies
fewer hitters. Only the feature LIST and the alpha VALUE were inherited.

Case #2 therefore applies, and this module does what that requires: H=200 is
treated as a NEW forecast specification, with its training target, fit
procedure, selected alpha, features, preprocessing and benchmarks frozen on
development data BEFORE any 2026 H=200 outcome is opened.

The frozen H=100 Contact Forecast is untouched. Nothing here modifies it, and
the Phase 2 H=100 result stands exactly as sealed.

## What may and may not be claimed

H=200 was NOT prespecified in R1, whose frozen grid used horizons 50 and 100.
The historical H=200 numbers are exploratory scoping and are labelled as such
everywhere. The `~82 windows` figure from that scoping run is recorded as an
exploratory power estimate ONLY: it is explicitly not a success threshold and
not a stopping rule, and the frozen success classification below makes no
reference to it.

## Season discipline

Development seasons 2022-2024 only. 2025 is sealed. 2026 is opened here for
CUTOFF-SIDE information only -- how many hitters reached 100 resolved BBE, how
many went on to 300, and how the two groups differ at the cutoff. No 2026
H=200 target is computed anywhere in this module, and
`assert_no_prospective_target` proves it on the returned audit.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from forecast.assemble import build_prediction_table
from forecast.features import build_window_features
from forecast.forecast_config import (
    DEFAULT_BOOTSTRAP_ALPHA,
    DEFAULT_BOOTSTRAP_REPS,
    DEFAULT_BOOTSTRAP_SEED,
    FORECAST_ANALYSIS_SEASONS,
    FORECAST_DATA_DIR,
    FORECAST_OUTPUTS_DIR,
    PROJECT_ROOT,
)
from forecast.metrics import DELTA_SIGN_CONVENTION
from forecast.phase2.phase2_config import (
    PHASE2_PERMITTED_TRAINING_SEASONS,
    SUCCESS_CLASSIFICATION,
    assert_phase2_seasons_allowed,
)
from forecast.phase2.phase2_windows import horizon_completion, order_events_for_phase2
from forecast.phase2.snapshot import load_contact_stage_ledger, resolve_snapshot
from forecast.ridge import ALPHA_GRID, FEATURE_SETS, fit_ridge, resolve_features, select_alpha
from forecast.windows import select_scored_eligible_events

logger = logging.getLogger(__name__)

H200_SPEC_VERSION = "contact_forecast_h200_spec_v1"
H200_OUTPUTS_DIR = PROJECT_ROOT / "outputs" / "forecast_phase2_h200"

H200_CUTOFF = 100
H200_HORIZON = 200
H200_TARGET = "target_realized_rv_per_100"
H200_MODEL = "D_full_contact_profile"
BENCHMARKS: tuple[str, ...] = (
    "league_mean",
    "shrunk_realized_persistence",
    "shrunk_deserved_persistence",
)
PRIMARY_BENCHMARK = "shrunk_deserved_persistence"

#: The answer to the provenance question, in machine-readable form.
H200_PROVENANCE_ANSWER: dict[str, Any] = {
    "question": (
        "Were the exploratory 100->200 predictions generated by the exact frozen H=100 "
        "Model D ridge coefficients and preprocessing, with only the evaluation target "
        "changed? Or was Model D refit on next-200-BBE targets?"
    ),
    "answer": "REFIT",
    "case": 2,
    "frozen_h100_coefficients_reused": False,
    "frozen_h100_preprocessing_reused": False,
    "frozen_h100_intercept_reused": False,
    "inherited_from_the_frozen_ridge": ["feature list", "alpha value"],
    "estimated_fresh_against_the_200_bbe_target": [
        "ridge coefficients",
        "intercept",
        "StandardScaler mean and scale",
    ],
    "evidence": {
        "intercept_h100": 5.2184,
        "intercept_h200": 5.8165,
        "training_rows_h100": 564,
        "training_rows_h200": 336,
        "coefficients_identical": False,
        "scaler_means_identical": False,
        "largest_coefficient_shift": {
            "feature": "launch_angle_p90",
            "h100": 0.6907,
            "h200": 0.2402,
        },
    },
    "consequence": (
        "H=200 is a NEW forecast specification, not the already-frozen Contact "
        "Forecast evaluated over a longer window. It is frozen here on development "
        "data before any 2026 H=200 outcome is opened."
    ),
    "must_not_be_called": [
        "the frozen Contact Forecast measured at 200 BBE",
        "a re-evaluation of the H=100 model",
        "prespecified in R1 -- R1's frozen grid used horizons 50 and 100 only",
    ],
    "frozen_h100_result_unchanged": True,
}

#: Recorded as exploratory context, and fenced off from the decision rule.
EXPLORATORY_POWER_ESTIMATE: dict[str, Any] = {
    "estimate_n_windows": 82,
    "derived_from": (
        "the exploratory 2024 scoping run: delta_MAE -0.3853 with a paired-difference "
        "SD of 1.780, via n = (1.96 * SD / delta)^2"
    ),
    "status": "EXPLORATORY POWER ESTIMATE ONLY",
    "is_a_success_threshold": False,
    "is_a_stopping_rule": False,
    "note": (
        "This number informed whether the experiment was worth running. It plays no "
        "part in the success classification, sets no minimum sample, and must never "
        "be used to decide when to stop collecting or to declare a result."
    ),
}


class H200SpecError(RuntimeError):
    """Raised when the H=200 specification cannot be frozen as required."""


# --------------------------------------------------------------------------
# The fit procedure, on development data only
# --------------------------------------------------------------------------


def build_development_windows(
    *,
    seasons: tuple[int, ...] = FORECAST_ANALYSIS_SEASONS,
    data_dir: Path = FORECAST_DATA_DIR,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """The 100 -> 200 development windows, with the frozen ladder attached."""
    assert_phase2_seasons_allowed(list(seasons))
    table, audit = build_prediction_table(
        seasons=seasons, data_dir=data_dir, cutoffs=(H200_CUTOFF,), horizons=(H200_HORIZON,)
    )
    return table, audit


def select_h200_alpha(table: pd.DataFrame) -> dict[str, Any]:
    """Select alpha by the FROZEN season-forward procedure, on the H=200 target.

    The procedure is the ridge stage's, unchanged: fit every candidate in the
    frozen `ALPHA_GRID` on 2022, score on 2023 by MAE, take the minimum. Only
    the target window differs. 2024 takes no part in selection, and 2026 is not
    read at all.
    """
    train = table[table["season"].astype(int) == 2022]
    validate = table[table["season"].astype(int) == 2023]
    if train.empty or validate.empty:
        raise H200SpecError("Alpha selection needs both a 2022 and a 2023 fold")
    selection = select_alpha(
        train, validate, model_name=H200_MODEL, target=H200_TARGET, alphas=ALPHA_GRID
    )
    selection["procedure_source"] = (
        "forecast.ridge.select_alpha -- the frozen ridge stage's procedure, unchanged"
    )
    selection["evaluation_season_used_in_selection"] = False
    selection["prospective_season_used_in_selection"] = False
    return selection


def fit_final_h200_model(table: pd.DataFrame, *, alpha: float) -> dict[str, Any]:
    """Fit the final H=200 model on every permitted development season.

    Trained on 2022-2024, matching the Phase 2 pattern for H=100: the seasons
    held out during development become legitimate training data for a
    prospective test. 2025 is sealed; 2026 is never fitted on.
    """
    train = table[table["season"].astype(int).isin(PHASE2_PERMITTED_TRAINING_SEASONS)]
    assert_phase2_seasons_allowed(sorted(int(s) for s in train["season"].unique()))
    if train.empty:
        raise H200SpecError("No permitted development windows to fit the final model on")
    fit = fit_ridge(train, model_name=H200_MODEL, alpha=alpha, target=H200_TARGET)
    record = fit.as_record()
    record["n_features"] = len(fit.features)
    record["target_column"] = H200_TARGET
    record["target_definition"] = (
        f"realized contact-result RV/100 over the next {H200_HORIZON} resolved "
        f"eligible BBE after the first {H200_CUTOFF}"
    )
    record["fitted_on"] = list(PHASE2_PERMITTED_TRAINING_SEASONS)
    record["prospective_season_used_in_fit"] = False
    return record


# --------------------------------------------------------------------------
# Survivorship
# --------------------------------------------------------------------------


def _cutoff_side_survivorship(
    features: pd.DataFrame, completion: pd.DataFrame, *, label: str
) -> dict[str, Any]:
    """Completion rate and how completers differ from non-completers AT THE CUTOFF.

    Uses only information available at the cutoff plus whether the hitter went
    on to accumulate the horizon. No target value is read.
    """
    merged = features.merge(
        completion[["batter", "season", "reached_cutoff", "completed_horizon"]],
        on=["batter", "season"],
        how="left",
    )
    reached = merged[merged["reached_cutoff"].fillna(False)]
    completers = reached[reached["completed_horizon"].fillna(False)]
    non_completers = reached[~reached["completed_horizon"].fillna(False)]

    feature_names, _ = resolve_features(FEATURE_SETS[H200_MODEL], reached)
    audited = ["std_realized_rv_per_100", "std_deserved_rv_per_100", *feature_names]
    differences: list[dict[str, Any]] = []
    for name in dict.fromkeys(audited):
        if name not in reached.columns:
            continue
        a = pd.to_numeric(completers[name], errors="coerce").dropna()
        b = pd.to_numeric(non_completers[name], errors="coerce").dropna()
        pooled_sd = float(pd.to_numeric(reached[name], errors="coerce").std(ddof=1))
        gap = float(a.mean() - b.mean()) if len(a) and len(b) else float("nan")
        differences.append(
            {
                "feature": name,
                "completer_mean": float(a.mean()) if len(a) else None,
                "non_completer_mean": float(b.mean()) if len(b) else None,
                "difference": gap,
                "standardized_difference": (
                    float(gap / pooled_sd)
                    if pooled_sd and np.isfinite(pooled_sd) and pooled_sd > 0
                    else None
                ),
            }
        )
    differences.sort(key=lambda row: -abs(row["standardized_difference"] or 0.0))
    n_reached, n_completed = int(len(reached)), int(len(completers))
    return {
        "population": label,
        "n_reaching_100_resolved_bbe": n_reached,
        "n_subsequently_reaching_300_total_resolved_bbe": n_completed,
        "n_not_completing": n_reached - n_completed,
        "completion_rate": (float(n_completed) / n_reached if n_reached else float("nan")),
        "cutoff_side_differences": differences,
        "largest_standardized_differences": differences[:5],
        "generalization_note": (
            f"An H={H200_HORIZON} result generalizes ONLY to hitters who subsequently "
            f"accumulate {H200_HORIZON} additional resolved eligible batted balls. It "
            "does not describe the hitters who did not, and it does not predict "
            "playing time, injury, roster survival or demotion."
        ),
    }


def development_survivorship(
    *, seasons: tuple[int, ...] = FORECAST_ANALYSIS_SEASONS, data_dir: Path = FORECAST_DATA_DIR
) -> dict[str, Any]:
    """The H=200 survivorship audit on development seasons."""
    per_season: dict[str, Any] = {}
    frames: list[pd.DataFrame] = []
    completions: list[pd.DataFrame] = []
    for season in seasons:
        ledger = pd.read_parquet(data_dir / f"walk_forward_ledger_{season}.parquet")
        resolved, _ = select_scored_eligible_events(ledger)
        ordered = order_events_for_phase2(resolved)
        features = build_window_features(ordered, H200_CUTOFF)
        completion = horizon_completion(ordered, cutoff=H200_CUTOFF, horizon=H200_HORIZON)
        per_season[str(season)] = _cutoff_side_survivorship(
            features, completion, label=f"development {season}"
        )
        frames.append(features)
        completions.append(completion)
    pooled = _cutoff_side_survivorship(
        pd.concat(frames, ignore_index=True),
        pd.concat(completions, ignore_index=True),
        label="development 2022-2024 pooled",
    )
    return {"pooled": pooled, "by_season": per_season}


def prospective_cutoff_audit(*, snapshot_label: str | None = None) -> dict[str, Any]:
    """The 2026 survivorship audit -- CUTOFF-SIDE ONLY, no target is computed.

    Reads who reached 100 resolved BBE, who went on to 300, and how those two
    groups differ at the cutoff. It never builds an H=200 window and never
    touches a next-200-BBE outcome.
    """
    snapshot = resolve_snapshot(label=snapshot_label)
    ledger, _ = load_contact_stage_ledger(snapshot)
    resolved, _ = select_scored_eligible_events(ledger)
    ordered = order_events_for_phase2(resolved)
    features = build_window_features(ordered, H200_CUTOFF)
    completion = horizon_completion(ordered, cutoff=H200_CUTOFF, horizon=H200_HORIZON)

    audit = _cutoff_side_survivorship(features, completion, label="prospective 2026")
    audit["snapshot_label"] = snapshot.label
    audit["snapshot_data_through"] = snapshot.data_through_date
    audit["h200_outcomes_opened"] = False
    audit["what_was_read"] = (
        "cutoff-side features from the first 100 resolved BBE, plus whether the hitter "
        "subsequently accumulated 200 more. No next-200-BBE run value was computed."
    )
    assert_no_prospective_target(audit)
    return audit


def assert_no_prospective_target(audit: dict[str, Any]) -> None:
    """Prove the prospective audit carries no H=200 outcome.

    Raises:
        H200SpecError: If any target-like key appears in the audit.
    """
    forbidden = ("target_", "_rv_per_100_next", "outcome_value")

    def _walk(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if any(
                    key.startswith(f) or f in key for f in ("target_realized", "target_deserved")
                ):
                    raise H200SpecError(
                        f"The prospective cutoff audit carries {key!r}, which is an "
                        "H=200 outcome. 2026 outcomes must not be opened yet."
                    )
                _walk(value)
        elif isinstance(node, list):
            for item in node:
                _walk(item)

    _walk(audit)
    del forbidden


# --------------------------------------------------------------------------
# The frozen specification
# --------------------------------------------------------------------------


def build_h200_specification(
    *, alpha_selection: dict[str, Any], model: dict[str, Any]
) -> dict[str, Any]:
    """The complete Phase 2 H=200 evaluation specification, frozen before 2026."""
    return {
        "spec_version": H200_SPEC_VERSION,
        "status": "FROZEN before any 2026 H=200 outcome was opened",
        "provenance_answer": H200_PROVENANCE_ANSWER,
        "experiment_question": (
            "Does a Contact Forecast model trained to predict 200-BBE future "
            "performance estimate that performance better than shrunk deserved, on a "
            "held-out season?"
        ),
        "not_prespecified_in_r1": (
            "R1's frozen window grid used horizons 50 and 100. H=200 is new. The "
            "historical 100 -> 200 numbers are exploratory scoping, not confirmatory."
        ),
        "design": {
            "cutoff": f"first {H200_CUTOFF} resolved eligible BBE",
            "target": (
                f"realized contact-result RV/100 over the next {H200_HORIZON} resolved eligible BBE"
            ),
            "target_column": H200_TARGET,
            "conditional_interpretation": (
                f"conditional on the hitter subsequently accumulating {H200_HORIZON} "
                "additional resolved eligible batted balls; it does not predict playing "
                "time, injury, roster survival, demotion, or whether the hitter reaches "
                "the horizon"
            ),
            "stage": "contact stage (Rc, E0, Rc - E0); never the full telescoping Rf",
        },
        "forecast_model_being_evaluated": {
            "architecture": H200_MODEL,
            "features": model["features"],
            "n_features": model["n_features"],
            "dropped_features": model["dropped_features"],
            "feature_provenance": (
                "the frozen Model D feature list, resolved by the frozen rules; no "
                "feature was added, removed or transformed for this horizon"
            ),
            "preprocessing": "StandardScaler fitted on training seasons only",
            "scaler_mean": model["standardization"]["mean"],
            "scaler_scale": model["standardization"]["scale"],
            "alpha": model["alpha"],
            "coefficients": model["standardized_coefficients"],
            "intercept": model["intercept"],
            "trained_on_seasons": model["fitted_on"],
            "n_train": model["n_train"],
            "distinct_from_the_frozen_h100_model": True,
        },
        "alpha_selection": {
            "procedure": alpha_selection["procedure_source"],
            "grid": list(ALPHA_GRID),
            "metric": alpha_selection["selection_metric"],
            "fit_seasons": alpha_selection["train_seasons"],
            "validation_season": alpha_selection["validation_season"],
            "selected_alpha": alpha_selection["selected_alpha"],
            "selected_alpha_at_grid_boundary": alpha_selection["selected_alpha_at_grid_boundary"],
            "evaluation_season_used_in_selection": False,
            "prospective_season_used_in_selection": False,
        },
        "benchmarks": {
            "primary": PRIMARY_BENCHMARK,
            "all": list(BENCHMARKS),
            "definitions": (
                "the frozen R1 ladder rungs, with shrinkage fitted on permitted "
                "development seasons only and re-proved causal against the evaluation "
                "season"
            ),
        },
        "metrics": {
            "primary": "MAE",
            "primary_comparison": f"delta_MAE = MAE(Contact Forecast) - MAE({PRIMARY_BENCHMARK})",
            "sign_convention": DELTA_SIGN_CONVENTION,
            "negative_delta_means": "the Contact Forecast is better",
            "interval": "paired 95% hitter-level bootstrap confidence interval",
            "secondary": ["RMSE", "R_squared", "Pearson", "Spearman"],
            "secondary_may_reclassify": False,
        },
        "required_analyses": [
            "survivorship audit",
            "stability and outlier sensitivity",
            "distribution-shift diagnostics",
        ],
        "success_classification": SUCCESS_CLASSIFICATION,
        "exploratory_power_estimate": EXPLORATORY_POWER_ESTIMATE,
        "season_discipline": {
            "training_seasons": list(PHASE2_PERMITTED_TRAINING_SEASONS),
            "sealed": [2025],
            "held_out_evaluation": [2026],
            "prospective_outcomes_opened": False,
        },
        "frozen_h100_result": "unchanged; this specification does not modify it",
        "bootstrap": {
            "reps": DEFAULT_BOOTSTRAP_REPS,
            "seed": DEFAULT_BOOTSTRAP_SEED,
            "alpha": DEFAULT_BOOTSTRAP_ALPHA,
            "cluster": "batter",
            "note": (
                "at a fixed cutoff each hitter contributes one completed window, so "
                "batter-clustered and ordinary hitter-level bootstrap coincide"
            ),
        },
    }


def extract_h200_key_results(outputs_dir: Path) -> dict[str, Any]:
    """The specification's own key facts, read back from its artifacts."""
    spec = json.loads((outputs_dir / "h200_specification.json").read_text())
    development = json.loads((outputs_dir / "h200_development_survivorship.json").read_text())
    prospective = json.loads((outputs_dir / "h200_prospective_cutoff_audit.json").read_text())
    # The upstream manifests are copied into this namespace so the freeze is
    # self-contained. That copy could go stale if a development stage were ever
    # re-frozen, so it is compared against the LIVE originals here rather than
    # only against itself.
    upstream_live: dict[str, bool] = {}
    for name in (
        "r1_freeze_manifest.json",
        "ridge_freeze_manifest.json",
        "hgb_freeze_manifest.json",
    ):
        live_path = FORECAST_OUTPUTS_DIR / name
        copy_path = outputs_dir / name
        upstream_live[name] = bool(
            live_path.exists()
            and copy_path.exists()
            and json.loads(live_path.read_text()).get("manifest_sha256")
            == json.loads(copy_path.read_text()).get("manifest_sha256")
        )

    return {
        "upstream_copies_match_live_manifests": upstream_live,
        "provenance_answer": spec["provenance_answer"]["answer"],
        "case": spec["provenance_answer"]["case"],
        "selected_alpha": spec["alpha_selection"]["selected_alpha"],
        "n_features": spec["forecast_model_being_evaluated"]["n_features"],
        "n_train": spec["forecast_model_being_evaluated"]["n_train"],
        "trained_on_seasons": spec["forecast_model_being_evaluated"]["trained_on_seasons"],
        "primary_comparison": spec["metrics"]["primary_comparison"],
        "success_classification_keys": sorted(spec["success_classification"]),
        "development_completion_rate": development["pooled"]["completion_rate"],
        "prospective_completion_rate": prospective["completion_rate"],
        "prospective_n_reaching_100": prospective["n_reaching_100_resolved_bbe"],
        "prospective_n_reaching_300": prospective["n_subsequently_reaching_300_total_resolved_bbe"],
        "prospective_outcomes_opened": spec["season_discipline"]["prospective_outcomes_opened"],
        "power_estimate_is_a_threshold": EXPLORATORY_POWER_ESTIMATE["is_a_success_threshold"],
    }


def assert_h200_specification(key_results: dict[str, Any]) -> None:
    """Refuse the freeze if the specification violates its own contract.

    Raises:
        H200SpecError: If the provenance answer changed, if 2026 outcomes were
            opened, or if the exploratory power estimate became a threshold.
    """
    if key_results["provenance_answer"] != "REFIT" or key_results["case"] != 2:
        raise H200SpecError(
            "The recorded provenance answer is no longer REFIT / case 2; the "
            "specification's whole justification rests on it."
        )
    if key_results["prospective_outcomes_opened"]:
        raise H200SpecError(
            "2026 H=200 outcomes have been opened. The specification must be frozen "
            "BEFORE any outcome is read."
        )
    if key_results["power_estimate_is_a_threshold"]:
        raise H200SpecError(
            "The exploratory power estimate has been turned into a success threshold, "
            "which it must never be."
        )
    stale = [
        name
        for name, matches in key_results.get("upstream_copies_match_live_manifests", {}).items()
        if not matches
    ]
    if stale:
        raise H200SpecError(
            f"The copied upstream manifest(s) {stale} no longer match the live frozen "
            "stages. The provenance chain would record a state that no longer exists."
        )
    if set(key_results["success_classification_keys"]) != {
        "established_incremental_success",
        "promising_but_inconclusive",
        "no_evidence_of_incremental_improvement",
        "evidence_against_incremental_value",
    }:
        raise H200SpecError("The success classification is not the prespecified four-way rule")


def render_specification_report(
    *, spec: dict[str, Any], development: dict[str, Any], prospective: dict[str, Any]
) -> str:
    """The human-readable frozen specification."""
    provenance = spec["provenance_answer"]
    model = spec["forecast_model_being_evaluated"]
    lines = [
        "# Contact Forecast -- Phase 2 H=200 evaluation specification (FROZEN)",
        "",
        f"**{spec['status']}.**",
        "",
        "## 1. How the exploratory 100 -> 200 result was produced",
        "",
        f"**Answer: {provenance['answer']} (case {provenance['case']}).**",
        "",
        "Model D was **refit** against next-200-BBE targets. It was NOT the frozen "
        "H=100 coefficients and preprocessing applied to a longer evaluation window.",
        "",
        "| element | reused from the frozen H=100 model? |",
        "|---|---|",
        f"| ridge coefficients | {provenance['frozen_h100_coefficients_reused']} |",
        f"| preprocessing (StandardScaler) | {provenance['frozen_h100_preprocessing_reused']} |",
        f"| intercept | {provenance['frozen_h100_intercept_reused']} |",
        "| feature list | yes |",
        "| alpha value (in the scoping run) | yes |",
        "",
        f"Evidence: intercept moved {provenance['evidence']['intercept_h100']} -> "
        f"{provenance['evidence']['intercept_h200']}; training rows "
        f"{provenance['evidence']['training_rows_h100']} -> "
        f"{provenance['evidence']['training_rows_h200']}; largest coefficient shift "
        f"`{provenance['evidence']['largest_coefficient_shift']['feature']}` "
        f"{provenance['evidence']['largest_coefficient_shift']['h100']} -> "
        f"{provenance['evidence']['largest_coefficient_shift']['h200']}.",
        "",
        "This must not be called: " + "; ".join(provenance["must_not_be_called"]) + ".",
        "",
        f"The frozen H=100 result is unchanged: {provenance['frozen_h100_result_unchanged']}.",
        "",
        "## 2. The experiment",
        "",
        f"> {spec['experiment_question']}",
        "",
        spec["not_prespecified_in_r1"],
        "",
        f"- Cutoff: {spec['design']['cutoff']}.",
        f"- Target: {spec['design']['target']}.",
        f"- Conditional: {spec['design']['conditional_interpretation']}.",
        f"- Stage: {spec['design']['stage']}.",
        "",
        "## 3. The frozen model being evaluated",
        "",
        f"- Architecture `{model['architecture']}`, {model['n_features']} features "
        f"({model['feature_provenance']}).",
        f"- Preprocessing: {model['preprocessing']}.",
        f"- Alpha **{model['alpha']}**, selected by "
        f"{spec['alpha_selection']['procedure']} on the "
        f"{spec['alpha_selection']['validation_season']} validation season "
        f"(fit on {spec['alpha_selection']['fit_seasons']}).",
        f"- Final fit on {model['trained_on_seasons']}, {model['n_train']} windows.",
        f"- Distinct from the frozen H=100 model: {model['distinct_from_the_frozen_h100_model']}.",
        "",
        "## 4. Benchmarks and metrics",
        "",
        f"- Primary benchmark: `{spec['benchmarks']['primary']}`. All: "
        + ", ".join(f"`{b}`" for b in spec["benchmarks"]["all"])
        + ".",
        f"- Primary metric: **{spec['metrics']['primary']}**.",
        f"- `{spec['metrics']['primary_comparison']}`; "
        f"negative means {spec['metrics']['negative_delta_means']}.",
        f"- Interval: {spec['metrics']['interval']}.",
        "- Secondary: " + ", ".join(spec["metrics"]["secondary"]) + ". "
        f"May reclassify a result: {spec['metrics']['secondary_may_reclassify']}.",
        "",
        "## 5. Prespecified success classification",
        "",
        "| classification | condition |",
        "|---|---|",
    ]
    for key in (
        "established_incremental_success",
        "promising_but_inconclusive",
        "no_evidence_of_incremental_improvement",
        "evidence_against_incremental_value",
    ):
        lines.append(f"| {key} | {spec['success_classification'][key]['condition']} |")
    power = spec["exploratory_power_estimate"]
    lines += [
        "",
        f"**{power['status']}**: ~{power['estimate_n_windows']} windows, "
        f"{power['derived_from']}. Is a success threshold: "
        f"{power['is_a_success_threshold']}. Is a stopping rule: "
        f"{power['is_a_stopping_rule']}. {power['note']}",
        "",
        "## 6. Survivorship, quantified before evaluation",
        "",
        "| population | reached 100 BBE | reached 300 total | completion rate |",
        "|---|---|---|---|",
    ]
    for label, audit in (
        ("development 2022-2024", development["pooled"]),
        ("prospective 2026", prospective),
    ):
        lines.append(
            f"| {label} | {audit['n_reaching_100_resolved_bbe']} | "
            f"{audit['n_subsequently_reaching_300_total_resolved_bbe']} | "
            f"{audit['completion_rate']:.3f} |"
        )
    lines += [
        "",
        "### How completers differ from non-completers at the cutoff",
        "",
        "Largest standardized differences (development, pooled). Positive means "
        "completers were higher at the cutoff.",
        "",
        "| feature | completers | non-completers | standardized difference |",
        "|---|---|---|---|",
    ]
    for row in development["pooled"]["largest_standardized_differences"]:
        lines.append(
            f"| `{row['feature']}` | {row['completer_mean']:.3f} | "
            f"{row['non_completer_mean']:.3f} | {row['standardized_difference']:+.3f} |"
        )
    lines += [
        "",
        development["pooled"]["generalization_note"],
        "",
        "## 7. Season discipline",
        "",
        f"- Training seasons: {spec['season_discipline']['training_seasons']}.",
        f"- Sealed, never read: {spec['season_discipline']['sealed']}.",
        f"- Held out for evaluation: {spec['season_discipline']['held_out_evaluation']}.",
        f"- **2026 H=200 outcomes opened: "
        f"{spec['season_discipline']['prospective_outcomes_opened']}.** The prospective "
        "audit above read cutoff-side features and completion counts only; no "
        "next-200-BBE run value was computed.",
        "",
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Freeze
# --------------------------------------------------------------------------

H200_ARTIFACTS: tuple[str, ...] = (
    "h200_provenance_answer.json",
    "h200_specification.json",
    "h200_frozen_model.json",
    "h200_development_survivorship.json",
    "h200_prospective_cutoff_audit.json",
    "h200_specification_report.md",
)

H200_SOURCE_MODULES: tuple[str, ...] = (
    "forecast/phase2/h200_spec.py",
    "forecast/phase2/phase2_config.py",
    "forecast/phase2/phase2_windows.py",
    "forecast/phase2/snapshot.py",
    "forecast/horizon_scope.py",
    "forecast/stage_freeze.py",
)

H200_CONCLUSION: dict[str, Any] = {
    "verdict": (
        "H=200 SPECIFICATION FROZEN -- no 2026 outcome has been opened, and no result is claimed."
    ),
    "statement": (
        "The exploratory 100 -> 200 scoping result was produced by REFITTING Model D on "
        "next-200-BBE targets (case 2), not by applying the frozen H=100 coefficients "
        "to a longer window. H=200 is therefore a NEW forecast specification. Its "
        "training target, fit procedure, selected alpha, feature list, preprocessing, "
        "benchmarks, metrics and four-way success classification are frozen here on "
        "development data only. The frozen H=100 Contact Forecast is unchanged. No "
        "2026 H=200 outcome has been read."
    ),
    "focal_comparison": (
        "delta_MAE = MAE(Contact Forecast) - MAE(shrunk_deserved), with a paired 95% "
        "hitter bootstrap interval. Negative favours the forecast. Not yet computed."
    ),
    "must_not_be_described_as": [
        "a result -- no 2026 outcome has been opened",
        "the frozen Contact Forecast measured over a longer window; it is a refit",
        "prespecified in R1, whose frozen grid used horizons 50 and 100 only",
        "confirmatory: the historical H=200 numbers are exploratory scoping",
    ],
    "preserved_negative_results": [
        "At H=50 the refit ridge was WORSE than shrunk deserved (delta_MAE +0.0370), "
        "which is the control that makes the horizon mechanism credible.",
        "The exploratory H=200 advantage was measured on 2024, a season already used "
        "as the evaluation fold for the ridge and HGB stages; it is worn, not fresh.",
        "Choosing H=200 after examining three horizons is cell selection, which is why "
        "it requires this freeze and an untouched test.",
    ],
}

H200_LIMITATIONS: tuple[dict[str, str], ...] = (
    {
        "id": "not_prespecified_in_r1",
        "statement": (
            "R1's frozen window grid used horizons 50 and 100. H=200 was chosen after "
            "examining three horizons on development data, so every historical H=200 "
            "number is exploratory scoping and cannot be confirmatory."
        ),
    },
    {
        "id": "new_model_not_the_frozen_one",
        "statement": (
            "The model frozen here is a REFIT with different coefficients, intercept "
            "and standardization from the frozen H=100 Contact Forecast. Results from "
            "the two are not interchangeable and must never be pooled."
        ),
    },
    {
        "id": "survivorship_is_stronger_at_h200",
        "statement": (
            "Requiring 300 resolved BBE conditions harder on playing time than the 200 "
            "the H=100 window needed. The result will generalize only to hitters who "
            "subsequently accumulate 200 additional resolved eligible batted balls, and "
            "the cutoff-side differences between completers and non-completers are "
            "quantified in the survivorship audit."
        ),
    },
    {
        "id": "power_estimate_is_not_a_rule",
        "statement": (
            "The ~82-window figure is an exploratory power estimate. It is not a "
            "success threshold, not a minimum sample and not a stopping rule, and the "
            "frozen classification makes no reference to it."
        ),
    },
    {
        "id": "2026_is_no_longer_pristine",
        "statement": (
            "2026 has already been used for the frozen H=100 Phase 2 evaluation. Its "
            "H=200 outcomes remain unexamined, which is what makes this a held-out "
            "test, but the season is not untouched in the way a wholly fresh one "
            "would be."
        ),
    },
)


def h200_freeze_spec() -> Any:
    """The `StageFreezeSpec` for this specification."""
    from forecast.stage_freeze import StageFreezeSpec

    return StageFreezeSpec(
        stage="h200_spec",
        version=H200_SPEC_VERSION,
        conclusion=H200_CONCLUSION,
        limitations=H200_LIMITATIONS,
        artifacts=H200_ARTIFACTS,
        source_modules=H200_SOURCE_MODULES,
        upstream_manifests=(
            "r1_freeze_manifest.json",
            "ridge_freeze_manifest.json",
            "hgb_freeze_manifest.json",
        ),
        key_results=extract_h200_key_results,
        checks=assert_h200_specification,
    )


def _json_default(value: Any) -> Any:
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        number = float(value)
        return number if np.isfinite(number) else None
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    raise TypeError(f"{type(value)!r} is not JSON-serializable")


def run(
    *,
    outputs_dir: Path = H200_OUTPUTS_DIR,
    research_dir: Path = FORECAST_OUTPUTS_DIR,
    data_dir: Path = FORECAST_DATA_DIR,
    snapshot_label: str | None = None,
) -> dict[str, Path]:
    """Build, write and freeze the H=200 specification. Opens no 2026 outcome."""
    outputs_dir.mkdir(parents=True, exist_ok=True)

    def _write(name: str, payload: dict[str, Any]) -> None:
        (outputs_dir / name).write_text(
            json.dumps(payload, indent=2, sort_keys=True, default=_json_default)
        )

    _write("h200_provenance_answer.json", H200_PROVENANCE_ANSWER)

    table, _ = build_development_windows(data_dir=data_dir)
    alpha_selection = select_h200_alpha(table)
    logger.info(
        "H=200 alpha selected on %s: %s",
        alpha_selection["validation_season"],
        alpha_selection["selected_alpha"],
    )
    model = fit_final_h200_model(table, alpha=float(alpha_selection["selected_alpha"]))
    _write("h200_frozen_model.json", {"alpha_selection": alpha_selection, "model": model})

    development = development_survivorship(data_dir=data_dir)
    _write("h200_development_survivorship.json", development)
    prospective = prospective_cutoff_audit(snapshot_label=snapshot_label)
    _write("h200_prospective_cutoff_audit.json", prospective)

    specification = build_h200_specification(alpha_selection=alpha_selection, model=model)
    _write("h200_specification.json", specification)
    (outputs_dir / "h200_specification_report.md").write_text(
        render_specification_report(
            spec=specification, development=development, prospective=prospective
        )
    )

    from forecast.stage_freeze import freeze_stage

    # The upstream manifests live in the research namespace; copy the frozen
    # stage manifests' hashes in by pointing the freeze at that directory for
    # the chain, while artifacts stay in this one.
    for name in (
        "r1_freeze_manifest.json",
        "ridge_freeze_manifest.json",
        "hgb_freeze_manifest.json",
    ):
        (outputs_dir / name).write_text((research_dir / name).read_text())
    manifest = freeze_stage(h200_freeze_spec(), outputs_dir=outputs_dir)
    logger.info("froze the H=200 specification: %s", manifest["manifest_sha256"])
    return {
        name: outputs_dir / name for name in (*H200_ARTIFACTS, "h200_spec_freeze_manifest.json")
    }


def main(argv: list[str] | None = None) -> int:
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outputs-dir", type=Path, default=H200_OUTPUTS_DIR)
    parser.add_argument("--research-dir", type=Path, default=FORECAST_OUTPUTS_DIR)
    parser.add_argument("--snapshot-label", type=str, default=None)
    args = parser.parse_args(argv)
    written = run(
        outputs_dir=args.outputs_dir,
        research_dir=args.research_dir,
        snapshot_label=args.snapshot_label,
    )
    for name, path in written.items():
        print(f"{name}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
